### ISSUE TITLE
js版本的建议

### ISSUE THREAD

**Issue by Googologyer** [defaultuser8848/safenote#1]
能不能搞个js版本

**Comment by defaultuser8848** [comment]
懒得搞了。
就算搞了也不给你。
另外我们不会以任何形式泄露任何类型的覆盖技术。

**Comment by Googologyer** [comment]
可惜了，我GitHub里面有公开技术。

________________________________
发件人: defaultuser8848 ***@***.***>
发送时间: 2024年5月14日 13:27
收件人: defaultuser8848/safenote ***@***.***>
抄送: Googology ***@***.***>; Author ***@***.***>
主题: Re: [defaultuser8848/safenote] js版本的建议 (Issue #1)


懒得搞了。
就算搞了也不给你。
另外我们不会以任何形式泄露任何类型的覆盖技术。

―
