### ISSUE TITLE
侵权投诉

### ISSUE THREAD

**Issue by Googologyer** [defaultuser8848/safenote#2]
您好，您的项目涉嫌违反 https://googologyer.github.io/notems/archiver.html 的Licence协议，属于侵权行为。因为你是Anonymous_user。

请立即对本项目进行相关处理，否则投诉到GitHub。

**Comment by defaultuser8848** [comment]
您好，这个项目是在我发现你这个网站之前上传的，而且语言都不一样，所以不涉及抄袭。
如果你执意这样认为，你可以把我起诉至你所在地区的法院（黑龙江省哈尔滨市阿城区人民法院）。

**Comment by defaultuser8848** [comment]
我想说的是，你的使用JS写的，这个使用python写的，而且我md5都没用过，怎么就侵权了？

**Comment by cmd1152** [comment]
笑死了，抄袭别人仓库，然后反过来说别人仓库是抄袭的

**Comment by Googologyer** [comment]
我哪里抄袭了？？？？
________________________________
发件人: cmd1152 ***@***.***>
发送时间: 2024年6月8日 11:57
收件人: defaultuser8848/safenote ***@***.***>
抄送: Googology ***@***.***>; Author ***@***.***>
主题: Re: [defaultuser8848/safenote] 侵权投诉 (Issue #2)


笑死了，抄袭别人仓库，然后反过来说别人仓库是抄袭的

―
